version: '3.8'

services:
  lucky-vote:
    build: .
    container_name: lucky-vote-app
    ports:
      - "80:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATA_FILE_PATH=/app/data/vote-data.json
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - lucky-vote-network

volumes:
  vote-data:
    driver: local

networks:
  lucky-vote-network:
    driver: bridge